application: pointer-party
version: 1
runtime: go
api_version: go1

handlers:
- url: /pointer.png
  static_files: pointer.png
  upload: pointer.png

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: _go_app
